// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentValue() {
  return window['go']['main']['Sorter']['GetCurrentValue']();
}

export function InsertMethod() {
  return window['go']['main']['Sorter']['InsertMethod']();
}

export function ShellMethod() {
  return window['go']['main']['Sorter']['ShellMethod']();
}

export function VectorGen(arg1) {
  return window['go']['main']['Sorter']['VectorGen'](arg1);
}
