// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentValue():Promise<Array<any>>;

export function InsertMethod():Promise<Array<any>>;

export function ShellMethod():Promise<Array<any>>;

export function SortBySelectionMethod():Promise<Array<any>>;

export function VectorGen(arg1:number):Promise<Array<number>>;
